name: bus-equity-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - jupyter
  - ipykernel
  - gdown
  - pytest         
